name: cancer_cell_analysis
description: "A new Flutter project for Cancer Cell AI Analysis."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  # UI & Utilities
  image_picker: ^1.0.4
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0        # ฟอนต์สวยๆ อ่านง่าย
  fl_chart: ^0.65.0           # กราฟสวยๆ สำหรับ Dashboard
  percent_indicator: ^4.2.3   # หลอดโหลดแบบวงกลม/เส้นตรง
  intl: ^0.18.1               # จัดการ format วันที่

  # Firebase (ชุดนี้แก้บั๊ก PigeonUserDetails แล้ว)
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true