name: cancer_cell_analysis
description: "A new Flutter project for Cancer Cell AI Analysis."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_vision: ^1.1.4
  sqflite: ^2.3.0
  path: ^1.9.0
  image: ^4.1.3  # เพิ่มตัวนี้
  path_provider: ^2.1.2
  csv: ^6.0.0
  share_plus: ^9.0.0
  shared_preferences: ^2.2.2
  
  # UI & Utilities
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  fl_chart: ^0.65.0
  percent_indicator: ^4.2.3
  intl: ^0.18.1

  # Firebase (ชุดเวอร์ชันใหม่ล่าสุดที่แก้บั๊ก PigeonUserDetails แล้ว)
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/labels/